name: Deploy to Azure Web App (Linux via OIDC)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: playground-web-lnx10930
  AZURE_RESOURCE_GROUP: playground-rg-central
  PACKAGE_PATH: webapp/app.zip

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd webapp
          npm ci

      - name: Zip app
        run: |
          cd webapp
          zip -r ../app.zip . -x "node_modules/*" ".git/*"

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy using Azure CLI
        run: |
          az webapp deploy \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --name "$AZURE_WEBAPP_NAME" \
            --type zip \
            --src-path "$PACKAGE_PATH"
