name: Deploy to Azure Web App (staging)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'webapp/**'
      - '.github/workflows/deploy-staging.yml'

env:
  AZURE_WEBAPP_NAME: playground-web-dev-wiehcnax
  AZURE_WEBAPP_SLOT: staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: staging-deploy
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json

      - name: Install deps
        working-directory: webapp
        run: npm ci

      - name: Package app
        run: |
          cd webapp
          zip -r ../app.zip . -x ".git/*" "node_modules/*"
          ls -lh ../app.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-zip
          path: app.zip

      - name: Deploy to staging slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT }}
          publish-profile: ${{ secrets.AZURE_STAGING_PUBLISH_PROFILE }}
          package: app.zip

      - name: Smoke test (health)
        run: |
          curl -fsS "https://${{ env.AZURE_WEBAPP_NAME }}-${{ env.AZURE_WEBAPP_SLOT }}.azurewebsites.net/health"

      - name: Smoke test (/)
        run: |
          curl -fsS "https://${{ env.AZURE_WEBAPP_NAME }}-${{ env.AZURE_WEBAPP_SLOT }}.azurewebsites.net/" | jq .